add project

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -44,15 +44,18 @@ jobs:
 #          done
 
 #          # Шаг для ожидания старта контейнера
-      - name: Wait for service to be ready
-        run: |
-          curl --silent --fail http://localhost:8080 || exit 1
+#      - name: Wait for service to be ready
+#        run: |
+#          curl --silent --fail http://localhost:8080 || exit 1
 
       - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'corretto'
+
+      - name: Pull images
+        run: docker-compose pull
 
       - name: Wait for containers to be ready
         run: |
