add project

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -35,18 +35,18 @@ jobs:
         run: |
           docker-compose up -d --build
 
-        # Шаг: Ожидаем, пока сервис будет готов к подключению
-      - name: Wait for API to be ready
-        run: |
-          until curl --silent --fail http://localhost:8080/api/health; do
-            echo "Waiting for API to be ready..."
-            sleep 5
-          done    
-
-#          # Шаг для ожидания старта контейнера
-#      - name: Wait for service to be ready
+#        # Шаг: Ожидаем, пока сервис будет готов к подключению
+#      - name: Wait for API to be ready
 #        run: |
-#          curl --silent --fail http://localhost:8080 || exit 1
+#          until curl --silent --fail http://localhost:8080/api/health; do
+#            echo "Waiting for API to be ready..."
+#            sleep 5
+#          done
+
+          # Шаг для ожидания старта контейнера
+      - name: Wait for service to be ready
+        run: |
+          curl --silent --fail http://localhost:8080 || exit 1
 
       - name: Set up JDK 17
         uses: actions/setup-java@v4
@@ -54,8 +54,10 @@ jobs:
           java-version: '17'
           distribution: 'corretto'
 
-#      - name: Run Docker
-#        run: docker-compose up -d
+      - name: Wait for containers to be ready
+        run: |
+         docker-compose up -d --build
+         sleep 10  
 
       - name: Run tests with Maven
         run: mvn test
