add project

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -11,30 +11,36 @@ jobs:
 
     runs-on: ubuntu-latest
 
-    services:
-      my_service:
-        image: eldarabdulhakov/sdet_practicum:latest
-        options: --health-cmd="curl --silent --fail http://localhost:8080/health || exit 1"  # Параметры для проверки здоровья
-        ports:
-          - 8080:8080  # Проброс порта из контейнера на хостовую машину
+#    services:
+#      my_service:
+#        image: eldarabdulhakov/sdet_practicum:latest
+##        options: --health-cmd="curl --silent --fail http://localhost:8080/health || exit 1"  # Параметры для проверки здоровья
+#        ports:
+#          - 8080:8080  # Проброс порта из контейнера на хостовую машину
 
     steps:
       - uses: actions/checkout@v4
 
-        # Шаг для настройки Docker
+#        # Шаг для настройки Docker
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
-          # Шаг для ожидания старта контейнера
-      - name: Wait for service to be ready
-        run: |
-          curl --silent --fail http://localhost:8080 || exit 1
+#          # Шаг для ожидания старта контейнера
+#      - name: Wait for service to be ready
+#        run: |
+#          curl --silent --fail http://localhost:8080 || exit 1
 
       - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'corretto'
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v1
+
+      - name: Run Docker Compose
+        run: docker-compose up -d
 
       - name: Run tests with Maven
         run: mvn test
